// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './unknown.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };
import glyphDataById from './glyphDataById.json' with { type: 'json' };

const bundle = {
  version: 0,
  family: 'Unknown',
  lineCap: 'round',
  fontUrl,
  fontFaceCSS: `@font-face { font-family: 'Unknown'; src: url(${fontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 1324,
  descender: -648,
  glyphData,
  glyphDataById,
  features: ["ccmp","fina","frac","init","liga","lnum","locl"],
} as const;

export default bundle;
